gems:
  - jekyll-seo-tag

title: Mukul Taneja
description: It is a web page which comprises information belongs to Mukul Taneja. Mukul Taneja is the only person who owns this page and this page contains information such as his primary interest, his background, his skills and his contact details across internet.
url: https://mukultaneja.github.io
author: Mukul Taneja
twitter:
  username: thecuriousmac
facebook:
  admins: Mac.theCreator
logo: https://mukultaneja.github.io/images/favicon.png
social:
  name: Mukul Taneja
  links:
    - https://in.linkedin.com/in/mukultaneja
    - https://www.facebook.com/Mac.theCreator
    - https://twitter.com/thecuriousmukul
    - https://github.com/mukultaneja
    - http://www.hackerearth.com/@mac.thecreator
    - https://keybase.io/benbalter
lang: en_US